# Generated by Django 5.2 on 2025-04-30 09:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0003_orderpaymentitem_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/staticfiles/images'), upload_to=''),
        ),
    ]
