# Generated by Django 5.2 on 2025-04-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0004_alter_userprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
