# Generated by Django 5.2 on 2025-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0005_alter_userprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentitem',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
