# Generated by Django 5.2 on 2025-05-05 12:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0006_alter_orderpaymentitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=cloudinary.models.CloudinaryField(default='dti-signature-images/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
