# Generated by Django 5.2 on 2025-05-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0008_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaymentitem',
            name='acting_accountant',
        ),
        migrations.AddField(
            model_name='orderpaymentitem',
            name='approver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
