# Generated by Django 5.2 on 2025-05-08 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0009_remove_orderpaymentitem_acting_accountant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentitem',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
